# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "jwellaryapp"
client_id = "cb0d3dbd679a2ff4582ad5a613d19143"
application_url = "https://soonest-severe-particles-gamma.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders"

[auth]
redirect_urls = [
  "https://soonest-severe-particles-gamma.trycloudflare.com/auth/callback",
  "https://soonest-severe-particles-gamma.trycloudflare.com/auth/shopify/callback",
  "https://soonest-severe-particles-gamma.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "amitstoreapp-dev.myshopify.com"
