# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = ""
client_id = "8b5687170cd198423c692344aa68fdfe"
application_url = "https://pk-tested-free-twist.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders"

[auth]
redirect_urls = [
  "https://pk-tested-free-twist.trycloudflare.com/auth/callback",
  "https://pk-tested-free-twist.trycloudflare.com/auth/shopify/callback",
  "https://pk-tested-free-twist.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "amitstoreapp-dev.myshopify.com"
